server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 1M;
    error_page 404 /error/404.html;
    error_page 500 /error/500.html;

    location / {
        root ./www;
        index index.html;
        methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        root ./www;
        methods GET POST;
        upload_store ./www/uploads;
    }

    location /uploads {
        root ./www;
        methods GET DELETE;
        autoindex on;
    }

    location /cgi-bin {
        root .;
        methods GET POST;
        cgi_ext .py .php;
    }
}
